name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-east-1
  TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  TF_VAR_s3_bucket_name: ${{ secrets.S3_BUCKET }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS credentials for Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_APPLY_ROLE }}
            aws-region: ${{ env.AWS_REGION }}
        
      - name: Configure AWS credentials for Plan
        if: github.event_name == 'pull_request'
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_PLAN_ROLE }}
            aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform changes
        if: github.event_name == 'pull_request'
        run: terraform plan
      
      - name: Apply Terraform changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve